<?php

// This file is automatically generated by Laravel...

return [
    \Core\Providers\AppServiceProvider::class,
    \Core\Providers\AuthServiceProvider::class,
    \Core\Providers\DatabaseServiceProvider::class,
    \Core\Providers\RouteServiceProvider::class,
];
